Release/v0.14.x
redhat-developer-demos/knative-tutorial-module-eventing pull request #9
Opened 2020-05-21 08:16 UTC by sebastienblanc

@kameshsampath

2020-05-21 18:02 UTC, kameshsampath requested changes
**Triggers and brokers:**

> Use the Knative Eventing Broker and Trigger Custom Resources to allow for CloudEvent attribute filtering. 

hyperlink CloudEvent.

some places where we mention 
> "Wait approximately 60 seconds for eventingaloha and eventingbonjour to terminate, scale-down to zero before proceeding."

It will be nice to add a console-input to watch the pods and see them terminate


**Verification** section 

typo  - http://default-broker.knativetutorial**}**.svc.cluster.local

**After curler pod creation**

Say to watch pods in "{tutorial-namespace}" and curler pod should be running (listing it via console-output)

Typo **($ and *)** for both aloha and bonjour curl commands

```shell
$ *curl -v "http://eventingaloha.knativetutorial.svc.cluster.local" \
-X POST \
-H "Ce-Id: say-hello" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: aloha" \
-H "Ce-Source: mycurl" \
-H "Content-Type: application/json" \
-d '{"key":"from a curl"}'*
```
Nice to have 
After each curl of bonjour and aloha, lets log the output of the events via console-output after watching each of those pods come up as a result of the event.

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/_attributes.adoc
> +:knative-sources-version: v0.14.0
this need to be v0.14.1

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/eventing-src-to-sink.adoc
>    sink:  #<1>
*ref:* is missing here

Check  https://knative.dev/docs/eventing/migration/ping/

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/eventing-src-to-sink.adoc
> +  eventinghello-pings-source
typo - eventinghello-ping-source

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/eventing-src-to-sink.adoc
> +You can xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs] to see the ping job source sending an event every 1 minute.
Link broken.  I am thinking if we can detail the logs via include ?

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/eventing-src-to-sink.adoc
can you please check the level header of services and sources. The have to be bold like how we do in serving https://redhat-developer-docs.github.io/knative-tutorial-staging/knative-tutorial-serving/basic-fundas.html#basics-see-what-you-have-deployed so that its visible. Otherwise it seem to have merged with the text

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
> += Channel and Subscribers
when you put he heading here please put like 
```asciidoc
= Page Title  <--  this will be overwritten with Knative Tutorial
include::_attributes.adoc[]
== Channels and Subscribers
```
That way its easier for the reader to understand what section you are in

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
>  apiVersion: messaging.knative.dev/v1alpha1
this should be changed to `messaging.knative.dev/v1beta1`

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
> +eventinghello-ch True  http://eventinghello-ch-kn-channel.knativetutorial.svc.cluster.local
Please variable `{tutorial-namespace}` in that way if we decide to change the namespace it will be easy that  the references will be updated. The reason why the resources was not replaced is in the line 51 *[source,bash]* there is no subs for attributes and macros like `[source,bash,subs="+macros,+attributes"]`.  Update that and use variables.

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
> +
Update https://github.com/redhat-developer-demos/knative-tutorial/blob/master/eventing/event-source.yaml to be inline with this change.

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
the output is not inline with actual output 
```NAME                        READY   REASON   SINK                                                                   AGE
event-greeter-ping-source   True             http://eventinghello-ch-kn-channel.knativetutorial.svc.cluster.local   8s```

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
> +kubectl -n {tutorial-namespace} get subscription.messaging.knative.dev
This should be a watch `watch kubectl -n {tutorial-namespace} get subscription.messaging.knative.dev` saying the subscriptions state "READY" should be `True`.

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
>  .Watch pods in the {tutorial-namespace}
can we have a console-input with `watch kubectl get -n {tutorial-namespace} get pods`

2020-05-21 18:02 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
For subsections Channel, source and subscriptions it will be great to bring it inline with https://redhat-developer-docs.github.io/knative-tutorial-staging/knative-tutorial-serving/basic-fundas.html#basics-see-what-you-have-deployed. Needs update of the section levels i..e `==`

2020-05-22 07:02 UTC, sebastienblanc commented on modules/ROOT/pages/eventing-src-to-sink.adoc
> +You can xref:{eventing-repo}/eventing.adoc#eventing-watch-logs[watch logs] to see the ping job source sending an event every 1 minute.
Link is working for me ... strange

2020-05-22 07:08 UTC, sebastienblanc commented on modules/ROOT/pages/channel-and-subscribers.adoc
> += Channel and Subscribers
Not sure I understand exactly what needs to be done here

2020-05-22 07:13 UTC, sebastienblanc commented on modules/ROOT/pages/channel-and-subscribers.adoc
> +
Not sure what to do here

2020-05-22 07:53 UTC, sebastienblanc commented on modules/ROOT/pages/channel-and-subscribers.adoc
>  .Watch pods in the {tutorial-namespace}
I made a note for that for later, it's a nice to have but I have no time today to rerun this part of the tutorial to capture the output.

2020-05-22 11:48 UTC, kameshsampath commented on modules/ROOT/pages/channel-and-subscribers.adoc
> +
I meant the YAML was not inline with new spec and api version of sources.knative.dev/v1alpha1

2020-05-29 13:38 UTC, merged